services:
  beta-db:
    image: postgres:15-alpine
    volumes:
      - beta_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kangoo
      - POSTGRES_USER=kangoo
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - kangoo-network_beta

  beta-web:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    command: gunicorn kangoo_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60 --keep-alive 5 --access-logfile - --error-logfile - --log-level info
    volumes:
      - beta_static_volume:/home/app/web/staticfiles
      - beta_media_volume:/home/app/web/media
    expose:
      - 8000
    environment:
      - DATABASE=postgres
      - SQL_HOST=beta-db
      - SQL_PORT=5432
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgresql://kangoo:${DB_PASSWORD}@db:5432/kangoo
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    depends_on:
      - beta-db
    restart: unless-stopped
    networks:
      - kangoo-network_beta
      - proxy


volumes:
  beta_postgres_data:
  beta_static_volume:
  beta_media_volume:

networks:
  kangoo-network_beta:
    driver: bridge
  proxy:
    external: true
